# Generated by Django 6.0.5 on 2026-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0003_community_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='following',
            options={'ordering': ['-followed_at'], 'verbose_name_plural': 'Following'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-liked_at'], 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='comment',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
