# Generated by Django 6.0.5 on 2026-06-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0004_alter_comment_options_alter_community_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
