# Generated by Django 6.0.5 on 2026-07-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0005_post_updated_at_alter_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reputation_score',
        ),
        migrations.RemoveField(
            model_name='community',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
