# Generated by Django 6.0.5 on 2026-07-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymous', '0006_remove_comment_reputation_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
