# Generated by Django 6.0.5 on 2026-06-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_knowncontacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowncontacts',
            options={'ordering': ['user__phone_number'], 'verbose_name_plural': 'Known Contacts'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
