# Generated by Django 6.0.5 on 2026-06-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0003_alter_knowncontacts_options_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
