# Generated by Django 6.0.5 on 2026-07-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0004_alter_messages_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowncontacts',
            options={'ordering': ['-added_at'], 'verbose_name_plural': 'Known Contacts'},
        ),
        migrations.RemoveField(
            model_name='messages',
            name='files',
        ),
        migrations.AddField(
            model_name='knowncontacts',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8),
        ),
    ]
