# Generated by Django 6.0.5 on 2026-07-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0005_alter_knowncontacts_options_remove_messages_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='updated_at',
        ),
    ]
