# Generated by Django 6.0.5 on 2026-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousalias',
            name='reputation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
