# Generated by Django 6.0.5 on 2026-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousalias',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/anonymous/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/users/profile_pictures/'),
        ),
    ]
