# Generated by Django 6.0.5 on 2026-06-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_anonymousalias_avatar_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymousalias',
            options={'verbose_name_plural': 'Anonymous Aliases'},
        ),
    ]
