# Generated by Django 6.0.5 on 2026-07-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousalias',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='anonymousalias',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
